version: "3.8"

services:
  backend:
    image: halahala1/smart-lock-backend:latest
    ports:
      - "3000:3000"
    depends_on:
      - face-service
    restart: on-failure                   
    env_file:
      - ./Smart-Lock-Server/.env
    networks:
      - smartlock

  face-service:
    image: halahala1/face-service:latest
    ports:
      - "5001:5001"
    volumes:
      - ./face-recognition-microservice/known_faces:/app/known_faces
    networks:
      - smartlock

networks:
  smartlock:
    driver: bridge
